import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import ProductModel from "@/lib/models/Product";

const seedData = [
  // ── TREADMILLS ────────────────────────────────────────────────────────────
  {
    name: "Jerai Treadmill Run RT",
    price: 185000,
    originalPrice: 220000,
    image: "https://images.unsplash.com/photo-1562771379-eafdca7a02f8?w=600&h=600&fit=crop",
    category: "Treadmills",
    rating: 4.9,
    reviews: 214,
    description: "Professional-grade treadmill with 3.0 HP AC motor, 25 km/h max speed, and 20 incline levels. Max user weight 185 kg. Pre-waxed reversible deck with advanced shock absorption. 4-window LED display. 1-year comprehensive warranty with 6 service visits.",
    stock: 10,
    badge: "Bestseller",
  },
  {
    name: "Jerai Treadmill Run TX",
    price: 210000,
    originalPrice: 260000,
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&h=600&fit=crop",
    category: "Treadmills",
    rating: 4.8,
    reviews: 143,
    description: "Professional-level space-efficient treadmill for commercial gyms. High-power AC motor, advanced cushioning deck, multi-program console with heart rate monitoring. Designed for intensive daily use.",
    stock: 7,
    badge: "Hot",
  },
  {
    name: "Jerai Curve Treadmill JCT-700",
    price: 250000,
    originalPrice: 310000,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=600&h=600&fit=crop",
    category: "Treadmills",
    rating: 4.9,
    reviews: 88,
    description: "Non-motorised curved treadmill for natural running biomechanics. Self-powered by user motion, burns 30% more calories than flat treadmills. Heavy-duty steel frame, ideal for HIIT and functional training.",
    stock: 5,
    badge: "New",
  },
  {
    name: "Jerai Treadmill Diamond 91 TFT",
    price: 150000,
    originalPrice: 185000,
    image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600&h=600&fit=crop",
    category: "Treadmills",
    rating: 4.7,
    reviews: 176,
    description: "Commercial treadmill with 10-inch TFT touch screen, built-in entertainment system, and Bluetooth connectivity. 2.5 HP AC motor, 22 km/h top speed, 15 incline levels. Ideal for hotel gyms and fitness centres.",
    stock: 8,
    badge: "Sale",
  },
  {
    name: "Jerai Treadmill Marathon",
    price: 130000,
    originalPrice: 160000,
    image: "https://images.unsplash.com/photo-1521804906057-1df8fdb718b7?w=600&h=600&fit=crop",
    category: "Treadmills",
    rating: 4.6,
    reviews: 132,
    description: "Endurance-focused marathon treadmill with wide running belt, 2.0 HP AC motor, 20 km/h speed, and 15 incline levels. Ergonomic handrails with pulse sensors. Suitable for clubs and home setups.",
    stock: 12,
    badge: "Sale",
  },

  // ── ELLIPTICALS ───────────────────────────────────────────────────────────
  {
    name: "Jerai Elliptical EPX",
    price: 120000,
    originalPrice: 148000,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop",
    category: "Ellipticals",
    rating: 4.8,
    reviews: 97,
    description: "Self-powered elliptical with 20 resistance levels and natural stride motion. Low-impact full-body workout, real-time performance tracking, ergonomic moving handles. No electricity required. 1-year comprehensive warranty.",
    stock: 9,
    badge: "New",
  },
  {
    name: "Jerai Elliptical E7",
    price: 95000,
    originalPrice: 118000,
    image: "https://images.unsplash.com/photo-1434682772747-f16d3ea162c3?w=600&h=600&fit=crop",
    category: "Ellipticals",
    rating: 4.7,
    reviews: 74,
    description: "Commercial elliptical cross-trainer with 18 resistance levels, adjustable stride length, and multi-grip handlebars. LED console with 10 workout programs. Smooth flywheel for natural elliptical motion.",
    stock: 11,
    badge: "Sale",
  },
  {
    name: "Jerai Elliptical Diamond EP",
    price: 135000,
    originalPrice: 168000,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=600&fit=crop",
    category: "Ellipticals",
    rating: 4.9,
    reviews: 56,
    description: "Premium Diamond series elliptical with large TFT display, 24 resistance levels, Bluetooth HR chest strap compatibility. Heavy-duty commercial frame handles 160 kg. Whisper-quiet drive system.",
    stock: 6,
    badge: "Hot",
  },

  // ── UPRIGHT BIKES ─────────────────────────────────────────────────────────
  {
    name: "Jerai Upright Bike UBX",
    price: 65000,
    originalPrice: 82000,
    image: "https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?w=600&h=600&fit=crop",
    category: "Upright Bikes",
    rating: 4.7,
    reviews: 118,
    description: "Commercial upright stationary bike with 20 resistance levels, adjustable seat and handlebars, LCD console tracking speed, distance, time, and calories. Compact footprint 46\" x 24\" x 59\".",
    stock: 15,
    badge: "Bestseller",
  },
  {
    name: "Jerai Upright Bike JUB 9",
    price: 85000,
    originalPrice: 105000,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=600&fit=crop",
    category: "Upright Bikes",
    rating: 4.8,
    reviews: 64,
    description: "Premium upright bike with 9-inch TFT screen, 24 resistance levels, and wireless heart rate monitoring. Interactive programs, Bluetooth connectivity, and ergonomic saddle. Built for high-usage commercial environments.",
    stock: 8,
    badge: "New",
  },
  {
    name: "Jerai Pro Spinning Bike",
    price: 45000,
    originalPrice: 58000,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop",
    category: "Upright Bikes",
    rating: 4.6,
    reviews: 193,
    description: "Heavy-duty indoor cycling / spinning bike with 20 kg flywheel, micro-adjustable resistance, padded racing saddle, and SPD-compatible pedals. Adjustable seat and handlebar in 4 directions. Belt drive for silent operation.",
    stock: 20,
    badge: "Sale",
  },

  // ── RECUMBENT BIKES ───────────────────────────────────────────────────────
  {
    name: "Jerai Recumbent Bike RBX",
    price: 75000,
    originalPrice: 94000,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=600&fit=crop",
    category: "Recumbent Bikes",
    rating: 4.7,
    reviews: 82,
    description: "Step-through recumbent bike with back-support seat and 20 resistance levels. Ideal for rehab and low-impact training. Easy mount/dismount, adjustable seat slide, pulse grip sensors on handlebars.",
    stock: 10,
    badge: "New",
  },
  {
    name: "Jerai Recumbent Bike JRB 9",
    price: 98000,
    originalPrice: 122000,
    image: "https://images.unsplash.com/photo-1559251606-c623743a6d76?w=600&h=600&fit=crop",
    category: "Recumbent Bikes",
    rating: 4.8,
    reviews: 47,
    description: "Premium recumbent bike with 9-inch TFT console, 24 resistance levels, wireless HR monitoring, and interactive fitness programs. Extra-wide contoured seat with lumbar support. Commercial-grade build.",
    stock: 6,
    badge: "Hot",
  },
  {
    name: "Jerai Pro Air Bike",
    price: 55000,
    originalPrice: 70000,
    image: "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=600&h=600&fit=crop",
    category: "Recumbent Bikes",
    rating: 4.9,
    reviews: 139,
    description: "Fan-resistance air bike for unlimited resistance that increases with effort. Full-body workout engaging arms and legs simultaneously. Heavy-duty steel frame, commercial-grade fan, oversized seat for comfort.",
    stock: 14,
    badge: "Bestseller",
  },

  // ── STRENGTH ──────────────────────────────────────────────────────────────
  {
    name: "Jerai Pec Fly / Rear Delt Machine",
    price: 145000,
    originalPrice: 185000,
    image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.8,
    reviews: 61,
    description: "Dual-function pec fly and rear delt machine with independent arm movement for balanced chest and rear shoulder development. Adjustable seat and starting position, weight stack included. Club Line Plus series.",
    stock: 6,
    badge: "Sale",
  },
  {
    name: "Jerai Lat Pull Down Machine",
    price: 135000,
    originalPrice: 170000,
    image: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.9,
    reviews: 98,
    description: "Commercial lat pull down with single/dual pulley options. Adjustable thigh pad, multiple grip positions, 100 kg weight stack. Targets latissimus dorsi, biceps, and upper back. Club Line Plus series.",
    stock: 8,
    badge: "Bestseller",
  },
  {
    name: "Jerai Leg Extension Machine",
    price: 125000,
    originalPrice: 158000,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.7,
    reviews: 73,
    description: "Biomechanically designed leg extension isolating the quadriceps. Adjustable back pad and roller, 100 kg weight stack, smooth cam mechanism for constant tension. Club Line Plus series.",
    stock: 9,
    badge: "Sale",
  },
  {
    name: "Jerai Seated Leg Curl Machine",
    price: 128000,
    originalPrice: 162000,
    image: "https://images.unsplash.com/photo-1544216291-5d4b000d367f?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.8,
    reviews: 55,
    description: "Seated leg curl machine with thigh stabiliser, adjustable roller cam, and 100 kg weight stack. Targets hamstrings through full range of motion. Comfortable seat with lumbar support. Club Line Plus series.",
    stock: 7,
    badge: "New",
  },
  {
    name: "Jerai Functional Training Tower",
    price: 195000,
    originalPrice: 245000,
    image: "https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.9,
    reviews: 44,
    description: "Twin adjustable pulley functional training tower with 11 height positions. Dual 75 kg weight stacks, full-length cable travel. Includes lat bar, rope, single handles. Ideal for cable crossovers, rows, and tricep work.",
    stock: 5,
    badge: "Hot",
  },
  {
    name: "Jerai Assisted Dip Chin Machine",
    price: 155000,
    originalPrice: 195000,
    image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&h=600&fit=crop",
    category: "Strength",
    rating: 4.8,
    reviews: 38,
    description: "Counter-weight assisted dip and chin-up machine for all fitness levels. 100 kg weight stack for assistance adjustment. Comfortable knee pad, multiple grip options for neutral, wide, and close-grip pull-ups.",
    stock: 6,
    badge: "Sale",
  },

  // ── HOME RANGE ────────────────────────────────────────────────────────────
  {
    name: "Jerai Multi Gym Home MG-4",
    price: 88000,
    originalPrice: 112000,
    image: "https://images.unsplash.com/photo-1625245488600-968b46b46b43?w=600&h=600&fit=crop",
    category: "Home Range",
    rating: 4.7,
    reviews: 167,
    description: "Complete home gym system for full-body training. Includes lat pulldown, chest press, leg developer, bicep curl station. 75 kg weight stack. Space-saving compact design fits in 1.8m x 1.2m. Ideal for home gyms.",
    stock: 12,
    badge: "Bestseller",
  },
  {
    name: "Jerai Adjustable Home Bench",
    price: 18500,
    originalPrice: 23000,
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=600&fit=crop",
    category: "Home Range",
    rating: 4.6,
    reviews: 234,
    description: "Multi-position adjustable weight bench for home training. 7 back positions, 3 seat positions, leg developer attachment. Sturdy steel frame rated 200 kg. Folds flat for storage. Includes transport wheels.",
    stock: 25,
    badge: "Sale",
  },
  {
    name: "Jerai Home Cardio Air Rower",
    price: 48000,
    originalPrice: 62000,
    image: "https://images.unsplash.com/photo-1521804906057-1df8fdb718b7?w=600&h=600&fit=crop",
    category: "Home Range",
    rating: 4.8,
    reviews: 112,
    description: "Air-resistance rowing machine for full-body home cardio. 10 damper settings, performance monitor showing split time, watts, and calories. Foldable for compact storage. Smooth chain drive. Handles up to 150 kg user weight.",
    stock: 14,
    badge: "New",
  },
  {
    name: "Jerai Home Spinning Bike JSB-3",
    price: 32000,
    originalPrice: 40000,
    image: "https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?w=600&h=600&fit=crop",
    category: "Home Range",
    rating: 4.5,
    reviews: 289,
    description: "Compact home spinning bike with 12 kg flywheel, belt drive, and micro-adjustable resistance. Padded saddle, adjustable handlebar, LCD display showing speed, time, and calories. Suitable for daily home cardio sessions.",
    stock: 30,
    badge: "Sale",
  },

  // ── ACCESSORIES ───────────────────────────────────────────────────────────
  {
    name: "Jerai Rubber Gym Flooring (Per Sqm)",
    price: 1800,
    originalPrice: 2400,
    image: "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=600&h=600&fit=crop",
    category: "Accessories",
    rating: 4.6,
    reviews: 321,
    description: "High-density interlocking rubber gym tiles, 20mm thickness. 100x100cm per tile, anti-fatigue, noise-dampening. Suitable for weight rooms, cardio areas, and functional training zones. Easy DIY installation.",
    stock: 500,
    badge: "Bestseller",
  },
  {
    name: "Jerai Cable Attachment Set",
    price: 8500,
    originalPrice: 11000,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=600&fit=crop",
    category: "Accessories",
    rating: 4.7,
    reviews: 145,
    description: "Complete cable attachment set including lat bar, short bar, rope, single handle (pair), and ankle strap. Chrome plated, compatible with all standard cable machines. Rotating carabiners for smooth motion.",
    stock: 45,
    badge: "Sale",
  },
  {
    name: "Jerai Barbell & Dumbbell Set (Home Kit)",
    price: 12500,
    originalPrice: 16500,
    image: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=600&h=600&fit=crop",
    category: "Accessories",
    rating: 4.8,
    reviews: 198,
    description: "Home weight set including 1.2m barbell, pair of dumbbell handles, 20 kg of cast iron plates, and spring collars. Ideal for home workouts. Knurled grip handles for secure hold. Plate sizes: 1.25 kg, 2.5 kg, 5 kg.",
    stock: 35,
    badge: "New",
  },
];

export async function POST() {
  try {
    await connectDB();
    await ProductModel.deleteMany({});
    const inserted = await ProductModel.insertMany(seedData);
    return NextResponse.json({ success: true, message: `${inserted.length} products seeded` });
  } catch (err) {
    console.error("Seed error:", err);
    return NextResponse.json({ success: false, error: "Seeding failed" }, { status: 500 });
  }
}
